pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                sh 'mvn --version'
                sh 'cd multi-stage-multi-agent && mvn compile'
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:25-alpine' }
            }
            steps {
                sh 'node --version'
                sh 'cd multi-stage-multi-agent && node app.js'
            }
        }
        stage('DB') {
            agent {
                docker { image 'mysql:9.7.0-oracle' }
            }
            steps {
                sh 'mysql --version'
            }
        }
    }
}
